### PR TITLE
Patches

### PR DESCRIPTION
**Pull request by sofar**
Various fixes ready for consumption.

### CODE REVIEW

**Comment by sofar** [comment]
I don't see these in your tree, did you reject them?

**Comment by darkersleeper** [comment]
don't know git, didn't know howto add some and not all

**Comment by sofar** [comment]
if you let me know which ones you would like to add, I can resubmit those separately

communication.

**Comment by darkersleeper** [comment]
description was ok

**Comment by sofar** [comment]
out of curiosity, what's do you think is wrong with the other 2 patches?

**Comment by darkersleeper** [comment]
nothing wrong with them, I just don't see a reason to have the licence stuff everywhere

**Comment by sofar** [comment]
It's entirely up to you, but the GPL license states that you should really do this, to make sure nobody attempts to get the benefit of the doubt. ("hey I followed this random link from google and found this code without a license text")

This is why almost all open source projects do this.

**Comment by darkersleeper** [comment]
if someone want to misuse free code, they will. no point in junking up lines to protect literally nothing

**Pull request closed without merging**
